-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:



-- Exercise 1: Count the number of trips in January 2022
-- 2463900
SELECT
  COUNT(*) AS total_trips_jan_2022
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  pickup_datetime >= '2022-01-01'
  AND pickup_datetime < '2022-02-01';



-- Exercise 2: Calculate the total revenue generated by taxi trips in 2022
-- 775917388.36
SELECT
  SUM(total_amount) AS total_revenue_2022
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  pickup_datetime >= '2022-01-01'
  AND pickup_datetime < '2023-01-01';

-- Exercise 3: Find the most popular pickup location
-- 132
SELECT
  pickup_location_id,
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY
  pickup_location_id
ORDER BY
  trip_count DESC
LIMIT 1;

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT
  EXTRACT(HOUR FROM pickup_datetime) AS pickup_hour,
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY
  pickup_hour
ORDER BY
  pickup_hour;

1	0	1001786
2	1	661286
3	2	440841
4	3	291413
5	4	200553
6	5	231502
7	6	567755
8	7	1051949
9	8	1396320
10	9	1561361
11	10	1719231
12	11	1867672
13	12	2017343
14	13	2058545
15	14	2205956
16	15	2263896
17	16	2250795
18	17	2450718
19	18	2575374
20	19	2325281
21	20	2000668
22	21	1918459
23	22	1768688
24	23	1429147

-- Exercise 5: Calculate the average trip distance
-- 6.077670271
SELECT
  AVG(trip_distance) AS avg_trip_distance
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`;

-- Exercise 6: Find the longest trip by distance
SELECT
  trip_distance,
  pickup_datetime,
  dropoff_datetime  
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
ORDER BY
  trip_distance DESC
LIMIT 1;

-- Exercise 7: Calculate the total number of passengers by payment type


-- Exercise 8: Find the most common drop-off location for trips paid by credit card


-- Exercise 9: Calculate the total number of trips that had more than 4 passengers


-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance